version: "3"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    hostname: monogdb
    ports:
      - 27017:27017
    networks:
      - restaurant-net
    volumes:
      - $PWD/data/mongodb:/data/db
      - $PWD/data/mongoinit/:/docker-entrypoint-initdb.d/
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  rabbitmq-manage:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 8080:15672
      - 5672:5672
    networks:
      - restaurant-net
    restart: always

networks:
  restaurant-net:
    driver: bridge
